#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prayer.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertmyList(myList instance);
    partial void UpdatemyList(myList instance);
    partial void DeletemyList(myList instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<myList> myLists
		{
			get
			{
				return this.GetTable<myList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.myList")]
	public partial class myList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Area;
		
		private string _Mosque;
		
		private string _Address;
		
		private System.TimeSpan _Fajar;
		
		private System.TimeSpan _Duhur;
		
		private System.TimeSpan _Asar;
		
		private System.TimeSpan _Magrib;
		
		private System.TimeSpan _Esha;
		
		private System.TimeSpan _Jummah;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAreaChanging(string value);
    partial void OnAreaChanged();
    partial void OnMosqueChanging(string value);
    partial void OnMosqueChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnFajarChanging(System.TimeSpan value);
    partial void OnFajarChanged();
    partial void OnDuhurChanging(System.TimeSpan value);
    partial void OnDuhurChanged();
    partial void OnAsarChanging(System.TimeSpan value);
    partial void OnAsarChanged();
    partial void OnMagribChanging(System.TimeSpan value);
    partial void OnMagribChanged();
    partial void OnEshaChanging(System.TimeSpan value);
    partial void OnEshaChanged();
    partial void OnJummahChanging(System.TimeSpan value);
    partial void OnJummahChanged();
    #endregion
		
		public myList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mosque", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Mosque
		{
			get
			{
				return this._Mosque;
			}
			set
			{
				if ((this._Mosque != value))
				{
					this.OnMosqueChanging(value);
					this.SendPropertyChanging();
					this._Mosque = value;
					this.SendPropertyChanged("Mosque");
					this.OnMosqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fajar", DbType="Time NOT NULL")]
		public System.TimeSpan Fajar
		{
			get
			{
				return this._Fajar;
			}
			set
			{
				if ((this._Fajar != value))
				{
					this.OnFajarChanging(value);
					this.SendPropertyChanging();
					this._Fajar = value;
					this.SendPropertyChanged("Fajar");
					this.OnFajarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duhur", DbType="Time NOT NULL")]
		public System.TimeSpan Duhur
		{
			get
			{
				return this._Duhur;
			}
			set
			{
				if ((this._Duhur != value))
				{
					this.OnDuhurChanging(value);
					this.SendPropertyChanging();
					this._Duhur = value;
					this.SendPropertyChanged("Duhur");
					this.OnDuhurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asar", DbType="Time NOT NULL")]
		public System.TimeSpan Asar
		{
			get
			{
				return this._Asar;
			}
			set
			{
				if ((this._Asar != value))
				{
					this.OnAsarChanging(value);
					this.SendPropertyChanging();
					this._Asar = value;
					this.SendPropertyChanged("Asar");
					this.OnAsarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magrib", DbType="Time NOT NULL")]
		public System.TimeSpan Magrib
		{
			get
			{
				return this._Magrib;
			}
			set
			{
				if ((this._Magrib != value))
				{
					this.OnMagribChanging(value);
					this.SendPropertyChanging();
					this._Magrib = value;
					this.SendPropertyChanged("Magrib");
					this.OnMagribChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Esha", DbType="Time NOT NULL")]
		public System.TimeSpan Esha
		{
			get
			{
				return this._Esha;
			}
			set
			{
				if ((this._Esha != value))
				{
					this.OnEshaChanging(value);
					this.SendPropertyChanging();
					this._Esha = value;
					this.SendPropertyChanged("Esha");
					this.OnEshaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jummah", DbType="Time NOT NULL")]
		public System.TimeSpan Jummah
		{
			get
			{
				return this._Jummah;
			}
			set
			{
				if ((this._Jummah != value))
				{
					this.OnJummahChanging(value);
					this.SendPropertyChanging();
					this._Jummah = value;
					this.SendPropertyChanged("Jummah");
					this.OnJummahChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
